default_agent: sleep_agent
agents:
  sleep_agent:
    name: sleep_agent
    entrypoint: src/main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::724772064768:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-0087aa1666
      execution_role_auto_create: false
      account: '724772064768'
      region: us-west-2
      ecr_repository: 724772064768.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-sleep_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: sleep_agent-kFTzKmC01Y
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:724772064768:runtime/sleep_agent-kFTzKmC01Y
      agent_session_id: c754fc4b-ce84-4887-8470-f53d53470531
    codebuild:
      project_name: bedrock-agentcore-sleep_agent-builder
      execution_role: arn:aws:iam::724772064768:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-0087aa1666
      source_bucket: bedrock-agentcore-codebuild-sources-724772064768-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
